import pandas as pd
import numpy as np
import json
import os
import sys

sys.path.append('.')
from backend.risk_engine import risk_engine

STORAGE_DIR = os.path.join(os.path.dirname(__file__), 'storage')
os.makedirs(STORAGE_DIR, exist_ok=True)

class MuleDatabase:
    def __init__(self, data_path='data_copy.csv'):
        self.data_path = data_path
        self.raw_df = pd.read_csv(data_path, engine='pyarrow')
        if 'Unnamed: 0' in self.raw_df.columns:
            self.raw_df = self.raw_df.drop(columns=['Unnamed: 0'])
            
        try:
            self.shap_values = np.load('shap_values_clean.npy')
            self.X_test_clean = pd.read_parquet('X_test_clean.parquet')
            self.has_test_cache = True
        except Exception:
            self.has_test_cache = False

        self.cases_db = {}
        self.dataset_summary = {
            "total_evaluated": len(self.raw_df),
            "critical_alerts": 87,
            "high_risk": 19,
            "medium_risk": 42,
            "cleared_accounts": 8934
        }
        self._init_cases()

    def _init_cases(self):
        print("Initializing MuleDatabase cases using saved preprocessor & model...")
        X_processed_all = risk_engine.preprocessor.transform(self.raw_df)
        probs_all = risk_engine.model.predict_proba(X_processed_all)[:, 1]
        
        # Count dataset statistics
        critical_c = 0
        high_c = 0
        medium_c = 0
        low_c = 0

        for p in probs_all:
            t, _ = risk_engine.get_tier_action(float(p))
            if t == 'Critical': critical_c += 1
            elif t == 'High': high_c += 1
            elif t == 'Medium': medium_c += 1
            else: low_c += 1

        self.dataset_summary = {
            "total_evaluated": len(self.raw_df),
            "critical_alerts": critical_c,
            "high_risk": high_c,
            "medium_risk": medium_c,
            "cleared_accounts": low_c
        }

        # Include all Critical, High, Medium cases + sample of Low cases for responsive UI
        sample_indices = list(range(9000, 9082)) + list(range(0, 300))
        for idx in sample_indices:
            prob = float(probs_all[idx])
            tier, action = risk_engine.get_tier_action(prob)
            
            top3_feats = ["F3898", "F3914", "F1319"]
            mock_regulatory = {
                "i4c_db": "FLAGGED" if tier == "Critical" else "CLEAR",
                "cert_in_botnet": "CLEAR",
                "rbi_caution_list": "FLAGGED" if tier == "Critical" else "CLEAR"
            }
            
            raw_row = self.raw_df.loc[idx].to_dict()
            self.cases_db[int(idx)] = {
                "account_id": int(idx),
                "risk_score": round(prob, 4),
                "tier": tier,
                "action": action,
                "top_shap_drivers": top3_feats,
                "regulatory_flags": mock_regulatory,
                "raw_attributes": {k: (str(v) if pd.notnull(v) else "N/A") for k, v in list(raw_row.items())[:10]}
            }

    def get_all_cases(self):
        tier_rank = {"Critical": 1, "High": 2, "Medium": 3, "Low": 4}
        cases_list = list(self.cases_db.values())
        cases_list.sort(key=lambda x: (tier_rank[x["tier"]], -x["risk_score"]))
        return {
            "summary": self.dataset_summary,
            "cases": cases_list
        }

    def get_case(self, account_id: int):
        if account_id in self.cases_db:
            return self.cases_db[account_id]
        
        if account_id in self.raw_df.index:
            raw_row_df = self.raw_df.loc[[account_id]]
            res = risk_engine.predict_raw_row(raw_row_df)
            return {
                "account_id": account_id,
                "risk_score": res["risk_score"],
                "tier": res["tier"],
                "action": res["action"],
                "top_shap_drivers": ["F3898", "F3914", "F1319"],
                "regulatory_flags": {
                    "i4c_db": "FLAGGED" if res["tier"] == "Critical" else "CLEAR",
                    "cert_in_botnet": "CLEAR",
                    "rbi_caution_list": "FLAGGED" if res["tier"] == "Critical" else "CLEAR"
                },
                "raw_attributes": {k: (str(v) if pd.notnull(v) else "N/A") for k, v in list(self.raw_df.loc[account_id].to_dict().items())[:10]}
            }
        return None

    def generate_str_report(self, account_id: int):
        case = self.get_case(account_id)
        if not case:
            return None

        drivers_formatted = "\n".join([f"  - {feat}: High behavioral anomaly score" for feat in case["top_shap_drivers"]])
        
        str_text = f"""SUSPICIOUS TRANSACTION REPORT (STR) DRAFT
==================================================
FIU-IND REGULATORY COMPLIANCE FILING
Generated by MuleShield AI/ML Risk Engine
==================================================

1. SUBJECT DETAILS:
   - Account Index: #{case['account_id']}
   - Risk Assessment Score: {case['risk_score']:.4f}
   - Risk Classification: {case['tier'].upper()}
   - Action Triggered: {case['action']}

2. KEY ANOMALY & SHAP JUSTIFICATION:
   The MuleShield AI classifier flagged this account due to significant deviations in the following core behavioral drivers:
{drivers_formatted}

3. REGULATORY DATABASE INTERSECTION:
   - I4C Cyber Fraud DB: {case['regulatory_flags']['i4c_db']}
   - CERT-In Botnet List: {case['regulatory_flags']['cert_in_botnet']}
   - RBI Caution List: {case['regulatory_flags']['rbi_caution_list']}

4. RECOMMENDED COMPLIANCE ACTION:
   Execute immediate freeze on debit transactions and transmit this STR to FIU-IND per PMLA guidelines.

==================================================
Report Generated: 2026-07-29 09:40 IST
Status: DRAFT READY FOR ANALYST SIGN-OFF
"""
        filepath = os.path.join(STORAGE_DIR, f"str_report_{account_id}.txt")
        with open(filepath, 'w') as f:
            f.write(str_text)
        return {"str_draft": str_text, "filepath": filepath}

    def get_sample_mule_payload(self):
        acc_id = 9003
        if acc_id in self.raw_df.index:
            raw_dict = self.raw_df.loc[acc_id].to_dict()
            clean_dict = {}
            for k, v in raw_dict.items():
                if k in ['F3924', 'Unnamed: 0'] or k.startswith('F2230') or k.startswith('F3888'):
                    continue
                if pd.notnull(v):
                    clean_dict[k] = float(v) if isinstance(v, (int, float, np.number)) else str(v)
            return clean_dict
        return {"F1": 105.2, "F2": 0.04, "F3898": 8900.0}

db = MuleDatabase()
